### ISSUE TITLE
Large fabric zones cause a server crash

### ISSUE THREAD

**Issue by EvieTheOwl** [SpaceClouds42/FabricZones#1]
9k x 9k fabric zone can cause a server to crash
Can probably just put a cap on how large zones can be or move zone calculations off to a separate thread :D

**Example from the server console**
```27.02 17:15:20 [Server] Server thread/WARN UncleBuster moved too quickly! -6.829590357885081,0.0,8.395375603845984
27.02 17:15:20 [Server] Server thread/WARN Can't keep up! Is the server overloaded? Running 12960ms or 259 ticks behind
```

**Crash report (timeout error)**: https://gist.github.com/profjb58/90f124b0b1597f9e5256fefbbec7eb99

**Comment by spaceclouds42** [comment]
I think I'm going to limit zones to a size of 100 by 100, because rendering borders for that size caused minimal to no lag, and cloaking caused a brief lag spike. I'll add a 'group' system that allows multiple zones to have the same settings all in one group, but only render the one zone that you're currently in to avoid crash.

**Comment by spaceclouds42** [comment]
Better idea, just don't render that many particles. If distance between player and particle is >20 blocks, stop rendering particles.

**Comment by spaceclouds42** [comment]
Also will need to run cloaking async so server doesnt hang
